server:
  port: 8080

spring:
  application:
    name: render-farm-orchestrator

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: ${KAFKA_ORCHESTRATOR_GROUP:orchestrator-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

render-farm:
  topics:
    jobs: ${KAFKA_TOPIC_JOBS:render.jobs}
    results: ${KAFKA_TOPIC_RESULTS:render.results}
  default-chunk-sec: 5.0
  storage-dir: ${STORAGE_DIR:./test_assets/storage}
